name: Python CICD

on:
    push:
        branches: [ main ]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2

            - name: Set up Python
              uses: actions/setup-python@v2
              with:
                python-version: 3.8

            - name: Install dependencies
              run: |
                python -m pip install --upgrade pip
                pip install tqdm colorama pytest
            
            - name: Run tests
              run: |
                pytest test_main.py
            
            - name: Run main script
              run: |
                python main.py
    
    deploy:
        needs: build
        runs-on: ubuntu-latest
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'

        steps:
            - uses: actions/checkout@v2

            - name: Set up Python
              uses: actions/setup-python@v2
              with:
                python-version: 3.8

            - name: Install dependencies
              run: |
                python -m pip install --upgrade pip
                pip install tqdm colorama
                if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

            - name: Deploy [simulated]
              run: |
                echo "Deploying to production..."
                python main.py
